README.md
appveyor.yml
demo/basic.html
package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue

Adds documentation and minor class changes.

---

README.md
demo/radioBasic.html
demo/radioBasic.js
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/data/node-generator.js
tests/unit/TreeView.spec.js
tests/unit/TreeViewNode.spec.js

Also includes documentation and demo updates.
Fixes #14

Radio buttons, refactoring for future inputs

---

docs/index.md
package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/unit/TreeViewNode.spec.js

Adds modelDefaults

---

.gitignore
docs/demo/addRemove.js
docs/demo/addRemove.md
docs/demo/demos.md
docs/index.md
package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/data/node-generator.js
tests/local/basic.js
tests/unit/TreeViewNode.spec.js
yarn.lock

 Adds creation of child nodes

---

docs/index.md
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/unit/TreeViewNode.spec.js

Remove customizations prop from Treeview.

---

package.json
src/components/TreeViewNode.vue

Updates selector matching call

---

package.json
yarn.lock

Updates dependency version to static #s

---

src/components/TreeViewNode.vue

Removes unused parentId prop

---

package.json

Version was incremented twice.

Reset version back to 0.10.1

---

docs/generateDocs.ps1
docs/index.md
docs/templates/base.html5
package.json

Fixes for github pages publishing

---

.browserslistrc
package.json
yarn.lock

Moves browserlist config, updates packages

---

docs/demo/addRemove.md
docs/demo/basic.md
docs/index.md
src/components/TreeViewNode.vue
tests/local/basic.html
tests/local/basic.js

Adds titles for node buttons

---

docs/generateDocs.ps1
docs/metadata.demo.yaml
package.json

- Local doc demos now point to the local build output
- Versioned published docs point to the versioned packages
fixes #110

Improves doc generation

---

docsrc/demo/customStyles.js
docsrc/demo/customStyles.md
docsrc/demos.md
docsrc/metadata.demo.yaml
docsrc/style/demo/classbased.css
docsrc/style/demo/demo.css
docsrc/style/demo/grayscale.css
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/unit/TreeView.spec.js

Adds skinning

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This includes a first crack at CONTRIBUTING.md and templates for Github functions.
closes #119

Adds meta-information for contributors

---

package.json
tests/unit/TreeViewNodeAria.spec.js
yarn.lock

Just a bit of package updating and cleanup.

Updates packages

---

docsrc/index.md
package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/unit/TreeView.eventHandling.spec.js
tests/unit/TreeView.spec.js
tests/unit/TreeViewAria.spec.js
tests/unit/TreeViewNode.customizations.spec.js
tests/unit/TreeViewNode.interactions.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js

Adds childrenPropNames to the model

---

package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
src/mixins/TreeViewAria.js
tests/unit/TreeViewAria.spec.js

Fixes some issues discovered with direct `children` references.

Fixes missed children references

---

package.json
vue.config.js

Also sets webpack to export 'default'
from the module automatically
Closes #140

Add main to package.json

---

docsrc/demos.md
docsrc/index.md
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/data/node-generator.js
tests/local/radioBasic.html
tests/local/radioBasic.js
tests/unit/TreeView.eventHandling.spec.js
tests/unit/TreeView.spec.js
tests/unit/TreeViewAria.spec.js
tests/unit/TreeViewNode.customizations.spec.js
tests/unit/TreeViewNode.interactions.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js

Changes radio button selection initialization from a prop on the TreeView component to a setting on the node specs themselves.
Closes #145

Refactors radio button initialization

---

docsrc/templates/base.html5

Adds missing siteroot to navbar links for docs.

Fixes sidebar nav links

---

src/components/TreeView.vue
src/components/TreeViewNode.vue
src/enums/selectionMode.js
src/mixins/TreeViewAria.js
src/mixins/TreeViewNodeAria.js
tests/unit/TreeView.eventHandling.spec.js
tests/unit/TreeView.spec.js
tests/unit/TreeViewAria.spec.js
tests/unit/TreeViewNode.customizations.spec.js
tests/unit/TreeViewNode.interactions.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js

Refactor selectionMode magic strings

---

docsrc/demos.md
docsrc/index.md
src/components/TreeView.vue
src/components/TreeViewNode.vue
tests/data/node-generator.js
tests/local/addRemove.html
tests/local/async.html
tests/local/async.js
tests/local/index.html
tests/local/slots.html
tests/local/slots.js
tests/unit/TreeViewNode.customizations.spec.js
tests/unit/TreeViewNode.interactions.spec.js
tests/unit/TreeViewNode.spec.js

Adds asynchronous loading of child node models.
Closes #13

Add async child node loading

---

docsrc/README.md
docsrc/demos.md
docsrc/index.md
src/components/TreeView.vue
src/components/TreeViewNode.vue
src/enums/dragDrop.js
src/enums/inputType.js
src/enums/mimeType.js
src/enums/selectionMode.js
src/mixins/TreeViewDragAndDrop.js
src/mixins/TreeViewNodeDragAndDrop.js
src/objectMethods.js
tests/data/node-generator.js
tests/local/dragDrop.html
tests/local/dragDrop.js
tests/local/index.html
tests/local/slots.html
tests/unit/TreeView.spec.js
tests/unit/TreeViewDragAndDrop.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js
tests/unit/TreeViewNodeDragAndDrop.spec.js
tests/unit/objectMethods.spec.js

Adds drag and drop support to the treeview.
closes #6

Add drag-and-drop support

---

package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
src/enums/event.js
src/mixins/TreeViewNodeAria.js
src/mixins/TreeViewNodeDragAndDrop.js

- Refactor custom prop refs to computeds
- Move private methods to module scope
- Refactor event names to a lookup
closes #166

Reduce component size private

---

src/components/TreeView.vue
src/components/TreeViewNode.vue
src/mixins/TreeViewAria.js
src/mixins/TreeViewNodeAria.js
src/mixins/TreeViewNodeDragAndDrop.js
src/objectMethods.js

Updates and adds JSDoc comments

---

src/components/TreeViewNode.vue
src/mixins/TreeViewDragAndDrop.js
tests/unit/TreeViewAria.spec.js
tests/unit/TreeViewDragAndDrop.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js

Generally adds more coverage.
Closes #168

Improve code coverage

---

docsrc/index.md
src/components/TreeViewNode.vue
tests/unit/TreeViewNode.customizations.spec.js

Add a wrapper div to child/loading area

---

docsrc/demos.md
src/components/TreeViewNode.vue
src/mixins/TreeViewAria.js
src/mixins/TreeViewNodeAria.js
tests/local/selection.js

Separate expanded state from expandable state

---

docsrc/demos.md
docsrc/index.md
docsrc/style/demo/classbased.css
docsrc/style/demo/grayscale.css
package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
src/mixins/TreeViewAria.js
src/mixins/TreeViewDragAndDrop.js
src/mixins/TreeViewNodeAria.js
src/mixins/TreeViewNodeDragAndDrop.js
tests/local/dragDrop.html
tests/local/slots.html
tests/unit/TreeView.spec.js
tests/unit/TreeViewAria.spec.js
tests/unit/TreeViewDragAndDrop.spec.js
tests/unit/TreeViewNode.customizations.spec.js
tests/unit/TreeViewNode.interactions.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js
tests/unit/TreeViewNodeDragAndDrop.spec.js
yarn.lock

- Shorten class/method names
- Shorten some methods
Closes #163

Reduce public size

---

appveyor.yml

Update pandoc version used (2.7.3 -> 2.11.4)

---

src/components/TreeViewNode.vue
src/mixins/TreeViewNodeAria.js
src/mixins/TreeViewNodeDragAndDrop.js

Internal alias to make code cleaner.
Closes #197

Alias model.treeViewSpec to tns

---

package.json
yarn.lock

Update packages 3.0.1

---

package.json
yarn.lock

Replace node-sass with sass dependency

---

package.json

Does what it says.
Closes #208

Remove IE11

---

appveyor.yml
docsrc/demos.md
docsrc/index.md
docsrc/metadata.demo.yaml
docsrc/style/docs.css
package.json
src/components/TreeView.vue
src/components/TreeViewNode.vue
src/mixins/TreeViewAria.js
src/mixins/TreeViewNodeAria.js
src/mixins/TreeViewNodeDragAndDrop.js
tests/local/addRemove.html
tests/local/async.html
tests/local/basic.html
tests/local/dragDrop.html
tests/local/radioBasic.html
tests/local/selection.html
tests/local/slots.html
tests/unit/TreeView.eventHandling.spec.js
tests/unit/TreeView.spec.js
tests/unit/TreeViewAria.spec.js
tests/unit/TreeViewDragAndDrop.spec.js
tests/unit/TreeViewNode.customizations.spec.js
tests/unit/TreeViewNode.interactions.spec.js
tests/unit/TreeViewNode.spec.js
tests/unit/TreeViewNodeAria.spec.js
tests/unit/TreeViewNodeDragAndDrop.spec.js
yarn.lock

Update treeview to Vue 3

---

appveyor.yml

Add shallow_clone: true for automation

---

src/components/TreeViewNode.vue
src/mixins/NodeDataNormalizer.js
src/mixins/TreeViewNodeAria.js

Move node normalization to a mixin

---

appveyor.yml

Update nodejs build version to 16

---

appveyor.yml

Only update doc default version for master tags

---

src/composables/nodeDataNormalizer.js
src/composables/treeViewNodeDragAndDrop.js
src/stories/Home.stories.mdx
tests/unit/TreeViewNodeDragAndDrop.spec.js

Add dataTransferEffectAllowed to TNS

---

src/components/TreeViewNode.spec.js
src/components/TreeViewNode.vue
src/composables/dragDrop/TreeViewNodeDragAndDrop.spec.js
src/composables/nodeDataNormalizer.js
src/stories/Examples.docs.mdx
src/stories/Home.stories.mdx
src/stories/definitions/TreeView.AddRemove.js

Add deleteNodeCallaback
